### ISSUE TITLE
Error at startup with 1.12.0 api

### ISSUE THREAD

**Issue by pomee4** [kvetinac97/EasyQUIZ#1]
Please make it possible to use the plugin with mcpe 0.11.*

**Comment by kvetinac97** [comment]
OK, udělám PM 1.5 verzi

**Comment by pomee4** [comment]
Please use english! I don't know u'r language :S

**Comment by ondraczsk** [comment]
Translate- Ok, i create Pm 1.5 version plugin.

Sorry my english is bad im czech

**Comment by kvetinac97** [comment]
Sorry, I read wrongly name of author of this issue. I thought it was ondraczsk issue, so I wrote answer is his language.

**Comment by pomee4** [comment]
NP :) Btw thanks for makeing it, it'll be awsome :)

**Comment by kvetinac97** [comment]
And yes, there are some small errors so it isn't working. Fixing now :)

**Comment by kvetinac97** [comment]
Fixed, try it

**Comment by kvetinac97** [comment]
Did it worked?

**Comment by pomee4** [comment]
It's okay now :3

**Comment by pomee4** [comment]
Emm nothing happen if players use /aw
And is question selecting random? :)

**Comment by kvetinac97** [comment]
This is PHP bug, nobody has solved it. The only way how get the plugin working is to make only one CORRECT_ answer. And this answer must be first and plugin won't randomize the answers, so the correct answer is always first :(

**Comment by kvetinac97** [comment]
Try this: https://github.com/kvetinac97/EasyQUIZ/releases/tag/1.0.1

**Comment by pomee4** [comment]
Thanks :)

**Comment by ondraczsk** [comment]
skype dáš :) ?

**Comment by kvetinac97** [comment]
Problem solved.
