### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by ondraczsk** [kvetinac97/EasyQUIZ#2]
květináči mě to nefunguje na serveru prostě sem zkusil to tam hodit a plugin nejde
tak to zkusim znovu a nwm.

**Comment by kvetinac97** [comment]
Jakou verzi PocketMine používáš?

**Comment by ondraczsk** [comment]
1255# nějáky developement build na fakaheda a je to dev build

**Comment by kvetinac97** [comment]
aha tak já ti dám link ze kterého to půjde ale počkej chvilku to bude trvat než ho najdu

**Comment by ondraczsk** [comment]
máš skype?

**Comment by kvetinac97** [comment]
Vyzkoušej to na té tvojí verzi mělo by to fungovat

**Comment by kvetinac97** [comment]
Fungovalo?

**Comment by kvetinac97** [comment]
Stáhni tohle: https://github.com/kvetinac97/EasyQUIZ/releases/tag/1.0.1
