### ISSUE TITLE
Please add A B C answer

### ISSUE THREAD

**Issue by ghost** [kvetinac97/EasyQUIZ#5]
Like /aw A to choose A answer

**Comment by kvetinac97** [comment]
Good idea for v1.1.1

**Comment by kvetinac97** [comment]
I added it, but new bug appeared. Like in v1.0.0 :/

**Comment by kvetinac97** [comment]
Added in v1.1.0. Check it at https://github.com/kvetinac97/EasyQUIZ/releases/tag/1.1.0/
