### ISSUE TITLE
First answer bug

### ISSUE THREAD

**Issue by pomee4** [kvetinac97/EasyQUIZ#6]
Only the first answer can be good.
Even if multiple correct answer exists.
question example:
"Melyik szerverrel szovetkezik az xperience mcpe?":
- "CORRECT_Kitconomy"
- "CORRECT_TheOld"
- "MMC"
  if players type /aw TheOld it wuld be good but it register as a wrong answer
  questin example 2
  "Melyik szerverrel szovetkezik az xperience mcpe?":
- "Kitconomy"
- "CORRECT_TheOld"
- "MMC"
  if players type /aw TheOld [or any answer] it does not do anything.

**Comment by kvetinac97** [comment]
So this bug hasn't been fixed? Mmm... I'l really look for fixing it

**Comment by pomee4** [comment]
No it hasn't
OK thanks :)

**Comment by kvetinac97** [comment]
I have used different method and fixed it. Check https://github.com/kvetinac97/EasyQUIZ/releases/tag/1.1.0/
