### ISSUE TITLE
# deleting in question list

### ISSUE THREAD

**Issue by pomee4** [kvetinac97/EasyQUIZ#7]
# lines are deleting in questions.yml if question deleting is turned on

**Comment by kvetinac97** [comment]
Give an example please

**Comment by pomee4** [comment]
Default example is deleting, not the question about knowing you, i mean the lines staring with "#"

**Comment by kvetinac97** [comment]
Yes, #examples are deleted too (if file is empty)... But it isn't bug, it's normal feature of the plugin (but worse than good)
